# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)

# Variables that are defined globally for the pipeline
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_STRATEGY: "clone"
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main$|^main_1_0$/
  STABLE_BRANCHES: /^main$/
  

include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-cmake-1.0.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges


# build on Windows system
windowsBuildDebug:
  stage: build
  extends: 
    - .build-win_17
    - .run-always
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DGTLAB_DEVTOOLS_DIR="$env:GTLAB_DEV_TOOLS" -DCMAKE_INSTALL_PREFIX=install-msvc2017-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install
    
windowsBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .build-win_20
    - .run-always
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DGTLAB_DEVTOOLS_DIR="$env:GTLAB_DEV_TOOLS" -DCMAKE_INSTALL_PREFIX=install-msvc2019-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install

windowsBuildRelease:
  stage: build
  extends: 
    - .build-win_17
    - .run-master-and-tags
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DGTLAB_DEVTOOLS_DIR="$env:GTLAB_DEV_TOOLS" -DCMAKE_INSTALL_PREFIX=install-msvc2017
    - cmake --build build --target install

windowsBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .build-win_20
    - .run-master-and-tags
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DGTLAB_DEVTOOLS_DIR="$env:GTLAB_DEV_TOOLS" -DCMAKE_INSTALL_PREFIX=install-msvc2019
    - cmake --build build --target install

# build on Linux system
linuxBuildDebug:
  stage: build
  extends: 
    - .build-linux_17
    - .run-always
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DGTLAB_DEVTOOLS_DIR=$GTLAB_DEV_TOOLS -DCMAKE_INSTALL_PREFIX=install-linux-dbg -DBUILD_UNITTESTS=ON -DBUILD_WITH_COVERAGE=ON
    - cmake --build build --target install
    
linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .build-linux_20
    - .run-always
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DGTLAB_DEVTOOLS_DIR=$GTLAB_DEV_TOOLS -DCMAKE_INSTALL_PREFIX=install-linux-dbg -DBUILD_UNITTESTS=ON -DBUILD_WITH_COVERAGE=ON
    - cmake --build build --target install

linuxBuildRelease:
  stage: build
  extends: 
    - .build-linux_17
    - .run-master-and-tags
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DGTLAB_DEVTOOLS_DIR=$GTLAB_DEV_TOOLS -DCMAKE_INSTALL_PREFIX=install-linux
    - cmake --build build --target install
 
linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .build-linux_20
    - .run-master-and-tags
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DGTLAB_DEVTOOLS_DIR=$GTLAB_DEV_TOOLS -DCMAKE_INSTALL_PREFIX=install-linux
    - cmake --build build --target install

# run tests using the binary built before
.testWinTemplate:
  tags: ["windows", "docker"]
  extends: 
    - .run-always
  before_script:
    - '& $env:GTLAB_UPDATE_TOOL up --confirm-command; $null'
  script:
    - $env:path = "$env:GTLAB_DEV_TOOLS\binDebug;$env:path"
    - cd build
    - .\H5UnitTest.exe --gtest_output=xml:unittests.xml
  artifacts:
    paths:
      - "build/unittests.xml"
    expire_in: 1 week
    reports:
      junit: build/unittests.xml

testWin:
  stage: test
  extends: 
    - .testWinTemplate
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-1_7-win
  needs: ["windowsBuildDebug"]

testWinUnstable:
  stage: unstableTest
  extends: 
    - .testWinTemplate
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-2_0-win
  needs: ["windowsBuildDebugUnstable"]

.testLinuxTemplate:
  tags: ["linux", "docker"]
  extends: 
    - .run-always
  before_script:
    # update to latest dev tools
    - '"$GTLAB_UPDATE_TOOL" up --confirm-command'
  script:
    - cd build
    - ./H5UnitTest --gtest_output=xml:unittests.xml
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
  artifacts:
    paths:
      - "build/unittests.xml"
    expire_in: 1 week
    reports:
      junit: build/unittests.xml

testLinux:
  stage: test
  extends: 
    - .testLinuxTemplate
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-1_7-buster
  needs: ["linuxBuildDebug"]

testLinuxUnstable:
  stage: unstableTest
  extends: 
    - .testLinuxTemplate
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-2_0-buster
  needs: ["linuxBuildDebugUnstable"]

code-coverage:
  stage: codequality
  tags: ["linux", "docker"]
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-1_7-buster
  extends: 
    - .run-always
  needs: 
    - linuxBuildDebug
  before_script:
    # make cmake find qt
    - export CMAKE_PREFIX_PATH=$QT_INSTALL_PATH
    # update to latest dev tools
    - '"$GTLAB_UPDATE_TOOL" up --confirm-command'
  script:
    - cd build
    - ninja test-coverage
    - mv test-coverage ..
  coverage: '/^\s{2}lines\.+:\s+(\d+.\d+\%)/'
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
  artifacts:
    paths:
      - "test-coverage"


.package:
  stage: package
  tags: ["docker", "linux"]
  extends: [".run-master-and-tags"]
  image: debian:buster
  script:
    - cp -r install-$toolchain-dbg/* install-$toolchain
    - mv install-$toolchain genh5-$toolchain
    - tar czf genh5-$toolchain.tar.gz genh5-$toolchain
  artifacts:
    name: "genh5-$toolchain"
    paths: ["genh5-$toolchain.tar.gz"]
  variables:
    toolchain: msvc2019
    GIT_STRATEGY: "none"

package-win-gtlab_2.0:
  extends: [".package"]
  needs: ["windowsBuildDebugUnstable", "windowsBuildReleaseUnstable"]
  variables:
    toolchain: msvc2019

package-win-gtlab_1.7:
  extends: [".package"]
  needs: ["windowsBuildDebug", "windowsBuildRelease"]
  variables:
    toolchain: msvc2017

package-linux-gtlab_2.0:
  extends: [".package"]
  needs: ["linuxBuildDebugUnstable", "linuxBuildReleaseUnstable"]
  variables:
    toolchain: linux

package-linux-gtlab_1.7:
  extends: [".package"]
  needs: ["linuxBuildDebug", "linuxBuildRelease"]
  variables:
    toolchain: linux

.conan:
  stage: package
  extends: [".run-always"]
  needs: []
  before_script:
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
  script:
    # Remove all local packages matching at-twk/unstable
    - conan remote add gitlab https://gitlab.dlr.de/api/v4/projects/20199/packages/conan --force
    - conan remove *$CONAN_CHANNEL_REFERENCE -f
    - conan create . $CONAN_CHANNEL_REFERENCE  -pr $CONAN_PROFILE -pr:b $CONAN_PROFILE
  variables:
    CONAN_LOGIN_USERNAME: ci_user
    CONAN_PASSWORD: ${CI_JOB_TOKEN}
    CONAN_CHANNEL_REFERENCE: at-twk/testing
    CONAN_PROFILE: default
    GIT_SUBMODULE_STRATEGY: "none"

# The linux package does not yet work, since the qt binaries are not provided
# and we cannot upload the qt binaries to out gitlab ci registry, due to a known
# limitation in gitlab
.conan-pkg 1/2:
  extends:
    - .conan
  image: conanio/gcc8
  tags: ["docker", "linux"]
  before_script:
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
    - conan profile update settings.compiler.libcxx=libstdc++11 default
  after_script:
    # Upload all packages. This should only include the newly created ones
    - if [ $CI_COMMIT_TAG ]; then conan upload *$CONAN_CHANNEL_REFERENCE  --all -c -r gitlab; fi

conan-pkg-windows:
  extends:
    - .conan
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/msvc-2019
  tags: ["docker", "windows"]
  before_script:
    - $env:path += ";c:\Python3;c:\Python3\Scripts"
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
  after_script:
      # Upload all packages. This should only include the newly created ones
    - $env:path += ";c:\Python3;c:\Python3\Scripts"
    - if ($CI_COMMIT_TAG -ne $null) {conan upload *$CONAN_CHANNEL_REFERENCE  --all -c -r gitlab }

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate
 
cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate

check-license:
   stage: codequality
   tags: ["docker", "linux"]
   extends: [".run-always"]
   needs: []
   image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/buster-dev
   before_script:
    - python3 -m pip install reuse
   script:
    - reuse lint
   variables:
     GIT_SUBMODULE_STRATEGY: "none"

pages:
  stage: badges
  extends: .pageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebug
    - linuxBuildDebug
    - testWin
    - testLinux
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWinUnstable
    - testLinuxUnstable
    - codingstyle
